# Generated by Django 3.1.8 on 2021-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='superhero_img',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
